# pv-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-pv-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pv-access-role
subjects:
  - kind: ServiceAccount
    name: jenkins-sa
    namespace: default  # Sesuaikan dengan namespace akun Jenkins Anda
